### ISSUE TITLE
Implement the Projects API and frontend

### ISSUE THREAD

**Issue by anandology** [pipalacademy/capstone#11]
The project author should be able to create/update a project through the API and see the project on the home page.

I suggest focus only the project details and skip the tasks for now.

Make sure you add tests for testing this functionality. 

## API

- [x] list projects
- [x] create/update a project
- [x] get a project
- [ ] delete a project

## CLI

```
$ export CAPSTONE_SITE=test
$ capstone-server projects list
$ capstone-server projects show rajdhani
$ capstone-server projects delete rajdhani
```

- [x] list
- [x] show
- [x] delete

## Frontend

- [x] The list of project shown on the home page
- [x] The project page shows the project details (except the tasks)

**Comment by nikochiko** [comment]
I think it might be okay to keep the delete functionality in the CLI only, and only allow the setting `is_published` to true or false from the API.
