### ISSUE TITLE
Git setup

### ISSUE THREAD

**Issue by anandology** [pipalacademy/capstone#15]
We need git setup with post-receive hook. 

For development, it will be just a local directory, for prod/staging, it will be git over https.

## Git post-receive hook

The post-receive hook should call an `/api/webhooks/post-receive` endpoint.

```
POST /api/webhooks/post-receive
Authorization: Bearer {config.git_post_receive_token}

{
    "repo_path": "/home/capstone/git/abcd1234/rajdhani.git",  
    "git_commit_hash: "..."
}
```

## Prod Setup 

The git-http-server should be run as a fasctcgi process as `capstone` user.

Try it and document the setup instructions.

**Comment by nikochiko** [comment]
With Gito, we won't be needing to initialise git on the starter code and saving it as `repo-git.zip` (and in fact causing a bug by setting up git twice).

I'm removing the logic to do that. We can directly use `repo.zip` now instead of `repo-git.zip`.

**Comment by nikochiko** [comment]
The post-receive hook will also need the username and project name.
Would we store that metadata with the repository, or send the gito repo id and fetch username/project from the db?
