### ISSUE TITLE
Deployments

### ISSUE THREAD

**Issue by anandology** [pipalacademy/capstone#16]
Deployment system for capstone. 

We need a deployment system that can be triggered on git-push.

For the scope of this issue, there will be a CLI for listing and triggering deploys. All deploys are tracked in the changelog.

## Approach

The deployment system will be designed to plugin different deployment backends.

Possible options could be:
- SimpleDeployment
- HamrDeployment
- NomadDeployment

For now, we'll go with `SimpleDeployment`.  It works in the following way:

- When deployed, the repo is copied to `{deployment_root}/{domain}`
- When a request comes for a domain, a new process in created to serve that request like a CGI

## Config

- `deployment_root`

## CLI

`deploys list` will list all the deploys in reverse chronological order.

```
$ capstone-server deploys list --user alice@example.com -p rajdhani
timestamp | project | user | git-hash | website-url
...
```

Force deploy an app.

```
$ capstone-server deploys new --user alice@example.com -p rajdhani
...
```

## Open Issues

- SimpleDeployment is not secure. A user delete the date of all the projects, including the capstone application directory. Or replace capstone with some malicious code. This is good enough for development, but we may need something more secure for prod.
- One option is to run the app in a Docker container for every request
- The other option is to go with Nomad

**Comment by nikochiko** [comment]
Blocked on running both apps in the same process.
Running a wsgi app would the environ and start_response ahead. With flask, i haven't found a way to get those two and pass them ahead.
We can run both capstone app and all the other deployment apps like a CGI server, but then even capstone would need to run like CGI.

**Comment by nikochiko** [comment]
Obsolete because we have nomad deployment only.
