### ISSUE TITLE
Run checks

### ISSUE THREAD

**Issue by anandology** [pipalacademy/capstone#17]
System run checks for a user project.

## Approach

The checks for a project are specified in a checks.py file along with the project.

The files of a project will be save in data dir.

```
data/sites/test-site/projects/rajdhani/checks.py
```

The checks will be run in a docker container, with a workdir mounted into it. 
```
workdir/
    requirements.txt
    checks.py
    repo/
```

The checks will run with `repo` as `$PWD`.

There repo will be the clone of user git repo.

The docker image could be build when the project is updated. 

Also, the checks need not run on the same machine where we the capstone is deployed. 

## CLI

There should a way to trigger the checks from CLI. That would start the execution in a docker container as described above.

```
$ export CAPSTONE_SITE=test-site
$ capstone-server checks run -p rajdhani -u alice@example.com
```

## Open Issues

- How to handle the checks where the application code is required. Will every run of a check clone it the repo?

**Comment by anandology** [comment]
This requires a little more thought and refinement.

**Comment by nikochiko** [comment]
Each check in checks.py will be a function that takes two arguments: `context` and `args`. context has some vars and the git url.

Each check would look like this, use the `@register_check` decorator and return `CheckStatus()` (pass) `CheckStatus.fail(()` or `CheckStatus.error()`

```
@register_check("check_http_redirect")
def check_http_redirect(context: Context, args: dict) -> CheckStatus:
    if not context.vars or "app_url" not in context.vars:
        return CheckStatus.error("app_url is not present in context vars")

    app_url = context.vars["app_url"]

    endpoint = args["endpoint"]
    expected_redirect_to = args["expected_redirect_to"]

    url = app_url + endpoint
    r = requests.get(url, allow_redirects=False)
    if not r.is_redirect:
        return CheckStatus.fail("URL didn't redirect:\n"
                                f"Endpoint: {endpoint}, Full URL: {url}\n"
                                f"Actual status code: {r.status_code}")

    if not r.next or r.next.url != expected_redirect_to:
        return CheckStatus.fail("URL didn't redirect to expected location:\n"
                                f"Endpoint: {endpoint}, Full URL: {url}\n"
                                f"Expected redirect to: {expected_redirect_to}\n"
                                f"Actual redirect to: {r.next and r.next.url}")

    return CheckStatus()
```

**Comment by anandology** [comment]
We don't need the `CheckStatus` class. raise `ValidationError` on check
failure. Any other exception marks the check as an error.

**Comment by nikochiko** [comment]
This is the approach we should take:

- Building docker image
<img width="447" alt="image" src="https://user-images.githubusercontent.com/37668193/228226169-3c378a5c-d285-41e9-9f6b-efa799a080c4.png">

- And running checks
<img width="484" alt="image" src="https://user-images.githubusercontent.com/37668193/228226296-388b14bd-1d7c-4970-81fd-c8b538a24bd7.png">

Both should run as background tasks.

**Comment by anandology** [comment]
I'll review this and get back to you shortly.

**Comment by nikochiko** [comment]
One more todo in this list would be to add methods to update the statuses in database. Setting the appropriate task to "In Progress" , and getting the status of a task from its checks.

I have added some of these methods during the start project task, but that should belong here and tests should be added for it.

**Comment by nikochiko** [comment]
This is blocked on https://github.com/pipalacademy/capstone/issues/28, because running the checks will need the project's requirements.txt and checks.py, as specified by the project author.

**Comment by nikochiko** [comment]
Done.

Runner: https://github.com/pipalacademy/capstone/commit/1cee191a3b65c77bcbc1353d4f4dabafebdfb19a, https://github.com/pipalacademy/capstone/commit/3457002866a30fe270b00fd13822bb2bc0b38802
Webhook/Task: https://github.com/pipalacademy/capstone/commit/82d0eefda639d9cf0cca41a17f667479788de998
Run checks without docker in dev mode: https://github.com/pipalacademy/capstone/commit/42c0f3a0f66894413ba360ec573748792074dc00
