### ISSUE TITLE
Dev setup

### ISSUE THREAD

**Issue by anandology** [pipalacademy/capstone#18]
- [x] tests
- [x] mypy (?)
- [ ] flake8 
- [x] logger
- [x] documentation
- [x] github actions

**Comment by anandology** [comment]
Finished everything except flake8, which is giving errors in almost every file. Will revisit flake8 later, closing this issue.

**Comment by anandology** [comment]
docs: https://pipalacademy.github.io/capstone/

**Comment by nikochiko** [comment]
> Finished everything except flake8, which is giving errors in almost every file. Will revisit flake8 later, closing this issue.

Yes, I remember that it has some strict defaults (two lines after each class/function, 80 character limit for each line).
It can read from a `.flake8.yml`configuration i think. We can use that.
