### ISSUE TITLE
Add tests for db module

### ISSUE THREAD

**Issue by nikochiko** [pipalacademy/capstone#19]
db module has been updated, and needs tests.

The tests should be conducted against a "capstone-test" database. This database is assumed to be empty while starting tests, and the teardown for tests should delete all created tables at the end.

**Tests:**

1. Generic db module tests:
  * These are to make sure that the base functionality is working correctly.
  * This should create a simple table, and test whether:
      * the base find, find_all, save, and delete functions are working correctly
      * the database defaults are working correctly
      * the database constraints are being held
      * arrays are being handled correctly
      * datetime is being handled correctly
2. Model tests
  * These are to make sure that the models functionality is working correctly
  * This should test whether:
      * the base model queries (find, find_all, update, save, delete) are working correctly
      * the serialization between db and model is working correctly
      * it is letting the database take care of setting defaults rather than sending null values in insert/update queries
      * serialization between model and json-dict is working fine

**Comment by anandology** [comment]
i think we should not create new tables for test. We just need to test the functionality of whatever classes that are written in the db module.

The `runtests.sh` already loads the schema in the test database and run the tests. You can add tests for each model.

**Comment by anandology** [comment]
And I don't we should see writing tests as a separate issue. I would like the code, tests, documentation all should go hand in hand.

**Comment by nikochiko** [comment]
> i think we should not create new tables for test. We just need to test the functionality of whatever classes that are written in the db module.

I want the models to only be data containers. The logic in Document base class shouldn't be overwritten by individual models. I want to have separate tests for that so that we can rely on it for new models, and that the data is converted between the right formats.

**Comment by anandology** [comment]
> I want the models to only be data containers. The logic in Document base class shouldn't be overwritten by individual models. I want to have separate tests for the queries and data conversion so that we can rely on it for new models.

Agreed. You could test that functionality do that testing the first model (or any one) that you write. You don't need to create a new table for doing that, which would unnecessarily complicate the testing flow. We'll need a different schema for tests and so on.

**Comment by nikochiko** [comment]
Ah, that makes sense. I'll do that with the Projects table. It has defaults
and array type and datetime.
