### ISSUE TITLE
capstone-server projects new

### ISSUE THREAD

**Issue by anandology** [pipalacademy/capstone#28]
As a system admin, I should be able to add a new project. When a new project is created, a git repo is initialized for with the project skeleton in gitto. The project can be updated by doing a git push that repo.

## The CLI

``` 
$ capstone-server projects new
title: Make your own Shell
name [make-your-own-shell]: shell

id: 45
name: shell
title: Make your own Shell
short_description: Make your own Shell
tags: []
git_url: https://git.capstone-staging.pipal.in/abcd1234/capstone-shell.git
```

The `capstone-server projects list` and `projects show` should also include the git_url.

## Approach

Have a `cookiecutter-capstone-project` directory and use it to create a new repo.

When a new project is created, the git repo is created using gitto and the project created using cookiecutter is added to the repo as "initial commit".

Have API endpoint `/api/projects/<name>/hook/<git-repo-id>`, this is registered as webhook for the gitto repo. When it is invoked the following things are done:

1. Add change log entry with status=pending
2. An offline task `update_project` is registered with project_id and changelog_id as arguments
3. Print a message "Enqueued a task to update the project abcd"

Also, add a web page `/projects/<project-name>/history` that shows the change log of all the git push and if any push failed to update, that would be displayed with error background.

### Offline task

The `update_project` task will update the project in a single db transaction. It will also update the a change log so that that the history page can show it.

The status of the change log entry will  be set to `running` at the beginning of the task and that gets changed to `success` or `failed` at the end of the task.

**Comment by nikochiko** [comment]
Log:

- [ ] Add gito_repo_id, git_url to project table in DB
- [ ] cookie cutter template
- [ ] Add CLI command that creates gito repo, db repo, then initialises gito repo with cookie cutter template
- [ ] API endpoint for webhook call

**Comment by nikochiko** [comment]
This is done

**Comment by nikochiko** [comment]
History page: https://capstone-staging.pipal.in/projects/shell/history

For the moment, there is no color for different status, but the updates are already sorted by latest, and the status is clearly visible. The logs are clearly shown when a header is clicked. This will work for the moment.

**Comment by anandology** [comment]
I see an unauthorised page. As a user what do you expect me to do?

**Comment by nikochiko** [comment]
Created #33 to address this.

**Comment by anandology** [comment]
I tried `capstone projects new` with `CAPSTONE_SITE=localhost`. 

It added a gitto webhook `http://localhost/...`. Git push to that gave 404.

When I tried to start this project, it failed with:

```
subprocess.CalledProcessError: Command '['unzip', '-d', '/tmp/tmp74bq0s_h', '/home/anand/github/pipalacademy/capstone/private/projects/build-your-own-shell/repo.zip']' returned non-zero exit status 9.
```

I would really like this software to be robust enough to not to get into this kind of error states.

**Comment by anandology** [comment]
One of the flaws in our approach is that we are using the site name to identify the the site and there is no way to find the URL from the site. 

I'm suggest replacing site-name with site-url in the CLI and find the site using the site-url. I'll create a separate issue for solving this.

**Comment by nikochiko** [comment]
We have the site domain for that.

Site URL can be found with "http://{site.domain}"

**Comment by anandology** [comment]
> Site URL can be found with "http://{site.domain}"

When site site is "localhost", which is the case for the dev instance, the URL is `http://localhost:5000/`, not `http://localhost/`. 

Also in production, the URL should be https, not http.

**Comment by anandology** [comment]
> One of the flaws in our approach is that we are using the site name to identify the the site and there is no way to find the URL from the site.
> 
> I'm suggest replacing site-name with site-url in the CLI and find the site using the site-url. I'll create a separate issue for solving this.

Created issue #34

**Comment by nikochiko** [comment]
> When site site is "localhost", which is the case for the dev instance,
the URL is http://localhost:5000/, not http://localhost/.

Ah, yes. I fixed that by setting up a local Caddy instance that proxies :80
to :5000.
That seemed quickest for development. There is a bigger issue with
development on Mac because docker doesn't support network="host", and so
the checks runner in container won't be able to talk to capstone app /
gitto on local host. I'll setup another issue for this.
