### ISSUE TITLE
Rename gito to gitto

### ISSUE THREAD

**Issue by nikochiko** [pipalacademy/capstone#30]
Changes will have to be made to code, comments, and database schema.

**Comment by anandology** [comment]
why would the name gito or gitto matter to the database schema? If we switch to using a different service to manage git, would you change the db schema again?

**Comment by nikochiko** [comment]
Maybe not. An integration with github or gitlab might work on a similar API as Gitto and would only require changes to the API wrapper functions.

Perhaps storing only the `repo_id` instead of `gito_repo_id` will work at this point.

Later on, even if the app logic changes to using some other service, the schema won't change.
If we decide to support multiple git integration providers, that can be supported too if the provider is saved.

**Comment by nikochiko** [comment]
commit also removes gito/ directory with the python Gito implementation.
