### ISSUE TITLE
Configuration management

### ISSUE THREAD

**Issue by nikochiko** [pipalacademy/capstone#31]
We need better configuration management. The CLI has to share configuration with capstone webapp and capstone task runner. The webapp and task runner can have their configuration duplicated in the supervisord config, but there's no straightforward way to do it for CLI.

Probably a good idea would be to have a `.env` file.

**Comment by anandology** [comment]
On Thu, Apr 6, 2023, 3:20 PM Kaustubh Maske Patil ***@***.***>
wrote:

> We need better configuration management. The CLI has to share
> configuration with capstone webapp and capstone task runner. The webapp and
> task runner can have their configuration duplicated in the supervisord
> config, but there's no straightforward way to do it for CLI.
>
> Probably a good idea would be to have a .env file.
>

The application takes config from env.

If .env works for you, nothing stopping you from using it. I may add them
to my bashrc.

From my experience, using environment variables works the best and the
twelve factor app echos that.

https://12factor.net/config

**Comment by nikochiko** [comment]
Added .env in this commit https://github.com/pipalacademy/capstone/commit/36d3ff77880acea08f52b73ca600b24409ed64ef

**Comment by anandology** [comment]
I think using dotenv is a bad idea. Please revert this change.

Having sensible defaults in the config.py is good enough for development
and i don't see a need for using dotenv.

**Comment by nikochiko** [comment]
Why though?

We are sharing a configuration between the webapp, task queue, and the CLI. While the webapp and task queue can get their config from env as specified by supervisor, the CLI can't get it in the same way. This feels like the simplest solution to share config.

**Comment by nikochiko** [comment]
> How would you specify production config when using cli? Modify the .env
file that is part of the repo?

Yup, okay. What do you think about changing the capstone user's `~/.bashrc` to add the variables there? That would only affect the CLI, and not the webapp/task runner.

We won't have to add a .env file in that case. The development configuration would be such that it works without any modifications.

**Comment by anandology** [comment]
Using . bashrc is perfectly fine.

**Comment by nikochiko** [comment]
This is done!
