### ISSUE TITLE
Use site_url instead of site_name in CLI

### ISSUE THREAD

**Issue by anandology** [pipalacademy/capstone#34]
One of the flaws in our approach is that we are using the site name to identify the the site and there is no way to find the URL from the site.

I'm suggest replacing site-name with site-url in the CLI and find the site using the site-url.

**Comment by nikochiko** [comment]
Fixed with a different approach. Anything that isn't localhost will have site_url with `https://...`, and localhost will be `http://localhost:5000`.
No change to the behaviour of CLI.
https://github.com/pipalacademy/capstone/commit/2b7d226d3ddfd8cd86d3dea45f8263b73b92480e
