### ISSUE TITLE
bug: database error when deleting a task that has a connected UserTaskStatus

### ISSUE THREAD

**Issue by nikochiko** [pipalacademy/capstone#38]
steps to reproduce:
1. setup a project with `capstone-server projects new`, keep the default task for git clone
2. start a project as a user. git clone and git push to this user_project repo, so that the first task is passing.
3. as the project author, delete this first task from the project's capstone.yml and make a push.

this will cause an error now and this operation will fail.

**Comment by nikochiko** [comment]
@anandology this bug is important. it doesn't allow us to update or delete tasks once they are added to a project and a user has started it. this is also a blocker to testing that functionality.

**Comment by anandology** [comment]
There are two solutions. 

1. When you delete a task, delete all the task status of all users as well.
2. Don't delete a task from the db, but just mark it as deleted. The queries must be tuned to ignore all the tasks that are marked deleted.

I feel the second one is a preferred option. 

In the same lines, what do you do you when a project is deleted after some users start that project?

**Comment by nikochiko** [comment]
As discussed on the call,
the delete method for project, task, check, user-project, user-task-status, user-check-status, etc. will have to be updated to delete the related rows individually. It is good to have the database restrict us when we try to delete a model that is being referenced from somewhere. But, it's not optimal for the learner's user experience to have things disappear without warning.

A better long-term solution would be to mark a deletion, let an existing learner know that there has been an update, and maybe let the user choose an action.

A user experience issue that remains is that the status of tasks for a learner would become stale after a project author updates the tasks or checks. This is out of scope for now.
