### ISSUE TITLE
Streamline local development

### ISSUE THREAD

**Issue by anandology** [pipalacademy/capstone#39]
Setting up a local dev instance is getting painful. We need a simple way to make it easier to setup a dev instance and run all the services.

I'm going to suggest a couple of approaches to solve this.

## Docker Compose

Dockerize everything and run in docker compose. 

The disadvantage is that it requires building docker image whenever a change is made or requires the code to be mounted as a volume.

I some how feel this adds a lot more complexity in the long run and not in favor of this approach.

## Procfile

The Procfile popularized by Heroku is a very simple approach to list the services to run. There are many implementations of Foreman, the application to run services from Procfile. The one like is ~[goreman](https://github.com/mattn/goreman), an implementation in Go~ [Honcho](https://github.com/nickstenning/honcho), an implementation of Foreman in Python.

This is the my recommendation. 

@nikochiko what do you suggest?

**Comment by nikochiko** [comment]
Agreed that Honcho would make dev setup simpler.
Looks good to me.

**Comment by nikochiko** [comment]
Let's implement the deployment part first. We would also need to accommodate that for a dev setup.

**Comment by anandology** [comment]
I'm almost done with this. Will move on to deployment after this.
