### ISSUE TITLE
Potential issue with add_auth_button

### ISSUE THREAD

**Issue by anandology** [pipalacademy/capstone#4]
## The Issue

The `add_auth_button` is modifying the layout which is a global variable. When two requests come at the same time one with a logged in user and another without, there is chance of race condition.

Imagine the scenario with  two requests with first being logged in and the second one without logged in. If the processing happens in the following order, both the users will see a login button.

```
REQ1 before request - add logout button to layout
    REQ2 before request - add login button to layout
REQ1 render page and serve the html
    REQ2 render page and serve the html
```

## Expected Behavior

A request should not be able to affect the other requests happening at the same time.

**Comment by nikochiko** [comment]
I think we can use an "Optional" element here with a render condition that runs a function to see if a user is authenticated or not.

**Comment by anandology** [comment]
> I think we can use an \"Optional\" element here with a render condition that runs a function to see if a user is authenticated or not.

That's a clever idea!
