### ISSUE TITLE
Streamline setting up gitto

### ISSUE THREAD

**Issue by anandology** [pipalacademy/capstone#40]
As mentioned in the commit fa8066df9c7f967248991f95a1e1f67665dc13a1, it is expected that the `gitto` is cloned at `../gitto` and built. This is cumbersome and we need to find a better way to handle this.

**Comment by anandology** [comment]
Option 1:

Run 

```
$ go install github.com/pipalacademy/gitto@latest
```

That installs gitto at `~/go/bin`.

Add `~/go/bin` to PATH from the Makefile so that Honcho can find it when starting it.

**Comment by anandology** [comment]
@nikochiko what do you think?

The `go install` could be part of a make rule.

**Comment by nikochiko** [comment]
Yeah this is good enough.

**Comment by nikochiko** [comment]
Added in https://github.com/pipalacademy/capstone/commit/d9c98d8b50ccd94018a63aaa9ae2073766514e8e
