### ISSUE TITLE
[bug] Registering a job for deploying an app with nomad doesn't check for error status, and assumes "OK" regardless. This should be checked.

### ISSUE THREAD

**Issue by nikochiko** [pipalacademy/capstone#49]
There are several things that need to be figured out here:

- [x] Log the error for server admins
- [x] Report the error for learners
- [x] Not to run checks after it fails

What is a learner expected to do when this happens and they don't know how to proceed?
- Report to server admins?
- Report to project author?

**Comment by anandology** [comment]
I have documented failure scenarios and what to do for each case in #51.
