### ISSUE TITLE
Deployment procedure and updating status of tasks

### ISSUE THREAD

**Issue by nikochiko** [pipalacademy/capstone#5]
There are three parts to this:
1. SSH Git server
2. Deployment (CD)
3. Running the checks -- running, then uploading to the server

For deployment, we will only consider deploying with Hamr. Hamr has the API to support deploying new apps and CD. One issue to figure out will be how to display the logs in case something goes wrong during deployment.

We will need to create a unique git repository URL for users, and add special instructions in the UI for this task. This should be a special kind of task, and a call should be made on whether this should use the same table as normal tasks or not.

The deployment script can be a YAML file that mentions the Hamr URL to hit when a repository is pushed.

For running the checks, we can use a checker service that will hit the Capstone API endpoint when it is finished with checks. This checker service could be a separate network process or a Python function.

**Comment by anandology** [comment]
done.
