### ISSUE TITLE
[bug] App name for Nomad deployment

### ISSUE THREAD

**Issue by nikochiko** [pipalacademy/capstone#50]
App name must include something about the site that makes it unique.
This is important for multi-tenancy, otherwise apps across different sites might conflict in their names. Currently the name is `{username}-{project_name}.local.pipal.in`. This template can be configured in `config.py`, and is already configured to be able to take a `site_name` as well, but we have to discuss how this would be used in multi-tenant hosting.

Some ideas:
- `{username}-{project_name}.{site_name}.pipal.in`  (TLS certificate will have to configured for each `*.{site_name}.pipal.in` separately).
- `{username}-{project_name}-{site_name}.pipal.in`

**Comment by anandology** [comment]
I think we should go with the first option. It requires creating a wildcard certificate for each site. 

While the application is multi-tenant, there may be installations that are single tenant and we shouldn't complicate their setup with multi-tenancy.
