### ISSUE TITLE
Changelog format for deployments

### ISSUE THREAD

**Issue by nikochiko** [pipalacademy/capstone#51]
The `update_user_project` task does two things:
- deployment
- run_checks

It has one changelog which currently only has information about checks, and not deployment.

This format needs to be updated to better fit our needs.

**Comment by anandology** [comment]
What is your suggestion? What should be logged? please show an example.

**Comment by nikochiko** [comment]
I was thinking about options for the same.

We should treat the `update_user_project` like a DAG, where if one task fails, the next task is aborted. Until then the status of both is pending.

This is the pseudocode for what I'm thinking:
```
deploy.status = "pending"
run_check.status="pending"
update_user_project()
    deploy.status = "running"
    run_deployment(...)
    | ok -> deploy.status = "success"
    | not ok -> deploy.status = "failed"; run_check.status = "aborted"; run_check.log = "Aborted because deployment failed"; return
    run_check(...)
    | ok -> run_check.status = "success"
    | not ok -> run_check.status = "failed"; return
```

The `check_run` logs need not be shown to the learner because errors within checks are handled, and will set the `CheckStatus.status` to "error", instead of error-ing here. If a check-run fails, server admins should be alerted because this is an internal server error. 

If the deployment fails, it would be because either:
- nomad rejected the job
- the health check for the job failed (this could be either because of an internal error or a user error). For example, it could be because the docker image couldn't be fetched, or because the container exited too early. 

In case of the first one, nomad would error immediately. In the second case, we would have to check the status with the jobID, and then detect it with the nomad API.
We would have to get the logs from the nomad API, and present it to the user. 

We should save details such as the `jobID` and `allocationID` to the changelog's details, so that it can be used for debugging.

I'm not sure whether the logs should be stored to database, file system, somewhere else, or fetched directly from nomad with the jobID and allocationID. 

The data from the event stream for that allocation could be part of the database.
This is short and describes the issue briefly. If for example, fetching the docker image fails, that would be logged to the event stream.
<img width="703" alt="image" src="https://user-images.githubusercontent.com/37668193/232512450-8a11e2bb-b7b4-46cf-8dac-712b3dcb1bb3.png">

**Comment by nikochiko** [comment]
One other option is to configure nomad to have some authentication, and let users see the logs there (anonymous policy).
https://developer.hashicorp.com/nomad/tutorials/web-ui/web-ui-access

**Comment by anandology** [comment]
> One other option is to configure nomad to have some authentication, and let users see the logs there (anonymous policy). https://developer.hashicorp.com/nomad/tutorials/web-ui/web-ui-access

No. The end users should not see Nomad at all. That is an implementation detail and it is too complex for the users to worry about.

**Comment by anandology** [comment]
> We should treat the `update_user_project` like a DAG, where if one task fails, the next task is aborted. Until then the status of both is pending.
> ...

Think more from the user's perspective. What are the failure scenarios?

1. Failed to build the application (eg. bad requirements.txt)
2. Failed to start the application (syntax error, or missing import)
3. Health checks failed (started on a different port, taking too long to respond)

In each case, we should say at what stage the failure is and show the appropriate log. 

**1. build failed**

Show the docker build log and that will include the error if build fails.

**2. failed to start**

Show the application logs 

**3. health check failed**

Show what health check failed, what is expected and what it got and give a link to look at the application logs. 

You may also want to show the number of times the application is restarted.

Does this makes sense? Did I miss anything?

**Comment by nikochiko** [comment]
This makes sense. Most likely, the second and third case would be the same,
unless we check the app long after it is deployed.

There is another case where the error could be an internal error, for
example when pushing to registry fails. But yes, I think in terms of user
errors these 2-3 are all that would be there.

Yes it makes sense to show application logs in 2/3rd case and build logs in
1st.

**Comment by nikochiko** [comment]
I have added logging and status catching for deployments.
It takes the status after some health checks are run. I noticed one issue locally where the "latest deployment" fetched wasn't actually the latest deployment, but I haven't dug deep into it.
Besides that, the system works fine. It currently waits for 60 seconds, and polls the status of latest deployment every 5 seconds until the deployment gets into a "Healthy" state.

One other potential issue about this is that if a deployment fails in between, like with the health check, the deployed code would be one (or more) version ahead of the checked code. We haven't thought about rolling back deployments upon failure yet. Not sure if we should worry about this just yet.

**Comment by nikochiko** [comment]
I did not add different changelogs for deployment/checks.
Rather, I added a new key called "stage" which can be either "deployment" or "checks". If the status of a changelog is not "success", the log key would have logs of this stage.
If stage is checks, then it can be assumed that deployments ran successfully.
