### ISSUE TITLE
mypy confuses nomad directory and the python-nomad package

### ISSUE THREAD

**Issue by nikochiko** [pipalacademy/capstone#52]
mypy confuses the two and the tests fail because it can't find attributes in the `nomad` directory that is at the top-level of this repository.

Shall we rename it to something, like `nomad-scripts` or `nomad-config` or `nomad-etc`?

**Comment by anandology** [comment]
> mypy confuses the two and the tests fail because it can't find attributes in the `nomad` directory that is at the top-level of this repository.

What does it say? It would be good to include the error message in the issue for context.

**Comment by anandology** [comment]
I don't see any errors. 

```
$ pytest --mypy nomad
========================================================= test session starts ==========================================================
platform linux -- Python 3.10.6, pytest-7.2.2, pluggy-1.0.0
rootdir: /home/anand/github/pipalacademy/capstone
plugins: mypy-0.10.3, flake8-1.1.1
collected 0 items                                                                                                                      

======================================================== no tests ran in 0.01s =========================================================
```

**Comment by nikochiko** [comment]
I had renamed the nomad directory to nomad-scripts. The errors are in the capstone/deployment.py module.

```
error: Module has no attribute "Nomad" [attr-defined]
```

This error https://github.com/pipalacademy/capstone/actions/runs/4738787699/jobs/8413007626
