### ISSUE TITLE
networking configuration on instance

### ISSUE THREAD

**Issue by nikochiko** [pipalacademy/capstone#54]
Nomad's docker driver doesn't take into consideration when it is running in a Docker Desktop environment like it has to on Mac.

There are two ways to expose a container's port: using network_mode = "host", and using static port configuration. Nomad tries to be smart and skips setting up port forwarding when network mode is configured to host. This works fine with docker linux, but not with docker desktop on macos, because network_mode = "host" is not supported.

In our current configuration, registry publishes its port on `127.0.0.1.:7979`. Nginx tries to proxy `registry.local.pipal.in` to this address and fails.

I didn't notice this issue locally because I had changed the job template to use `host.docker.internal:{{ .Port }}` instead of the one in the codebase `{{ .Address }}:{{ .Port }}`, but I noticed it when trying to deploy rajdhani project to capstone. 

I think a good workaround, and to avoid such inconsistencies in the future, would be to use the [`extra_hosts`](https://developer.hashicorp.com/nomad/docs/drivers/docker#extra_hosts) configuration to allows forward `host.docker.internal` to the host.

Or, I think Nomad also supports using templates in task configurations.
We could use the private IP with static port for preset jobs, and then not have to do any special workarounds.

**Comment by anandology** [comment]
I would like to avoid spending time on the quirks of running Nomad on Mac,
at least in these initial stages. Would it be okay for you if we figure out
a way to run Nomad on your dev server, but make it look like a local one
with some ssh port forwarding magic?

**Comment by nikochiko** [comment]
That would work, yes.
