### ISSUE TITLE
Add a minimal footer

### ISSUE THREAD

**Issue by anandology** [pipalacademy/capstone#58]
Add a minimal footer to Capstone. 

```
----


About  Github                                                                  © 2023 Pipal Academy LLP 
```

This requires customization for every site, but we'll revisit that part later.

**Comment by nikochiko** [comment]
Does copyright here mean for the content that is hosted on the website?

**Comment by nikochiko** [comment]
Preview on desktop:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/37668193/234970449-62ae45eb-4631-4274-9dcd-3116ce78b6b6.png">

Preview on mobile:
<img width="324" alt="image" src="https://user-images.githubusercontent.com/37668193/234970740-0f05e6b5-d989-47a6-9d2b-dc1e8586e499.png">
