### ISSUE TITLE
Courses in Capstone

### ISSUE THREAD

**Issue by anandology** [pipalacademy/capstone#65]
## Overview

Capstone will have many learning resources. There will be many kinds of resources like courses, tutorials, workshops, exercises, projects etc. While these have subtle differences, capstone should be able to accommodate different kinds of resources. 

We already have projects, but it would be good to add courses now.

## Approach

Rather than inventing a new way to create courses, it would be good to write importers for popular format like mdbook and mkdocs. I suggest starting with mdbook as that is simpler.

## Technical Architecture

Since we are going to have many kinds of resources, it would be good to think about how to structure the database and code for extensibility. It would be nice to think of some kind of plugin architecture to enable/disable different modules.

However, this is not a primary concern and it is perfectly fine to refactor later to meet this requirement.

## Topics

Courses introduces the following topics.

- Courses
- Lessons
- Course Outline
- Course Author (?)

## Open Issues

- What are the interactions between courses and users/learners? Do they have to start a course to see it? What are the incentives to start a course?

**Comment by nikochiko** [comment]
Done.
