### ISSUE TITLE
Course Package Format

### ISSUE THREAD

**Issue by anandology** [pipalacademy/capstone#67]
The Capstone Package Format #66 defines how resources are packaged. This issue further defines the structure of the contents for a course.

A course will contain:
- course outline
- lessons
- static resources

## Structure

TODO

**Comment by nikochiko** [comment]
Directory tree:
```
metadata
contents/
|-- course.json
|-- modules/
|   |-- module_1/
|   |   |-- lesson_1.html
|   |   |-- lesson_2.html
|   |   |-- ...
|   |   |-- static/
|   |   |   |-- ...
|   |-- module_2/
|   |   |-- ...
```

Course must contain a `course.json`:
```json
{
  "name": "course_name",
  "title": "Course Title",
  "description": "Course Description",
  "author": "Course Author",  # not right now?
  "modules": [
    {
      "name": "module_1",
      "title": "Introduction to Topic",
      "lessons": [
        {
          "name": "lesson_1",
          "title": "Overview of Topic",
          "path": "modules/module_1/lesson_1.html"
        },
        {
          "name": "lesson_2",
          "title": "Subtopic 1",
          "path": "modules/module_1/lesson_2.html"
        },
        ...
      ]
    },
    {
      "name": "module_2",
      "title": "Topic 2",
      "lessons": [
        ...
      ]
    },
    ...
  ]
}
```

The exact directory structure is not that important.
Any relative links in the HTML must be relative to itself.

**Comment by anandology** [comment]
Lessons could be text (or html), video or quiz/exercise. We need to leave room for that extension. 

I suggest adding a "kind": "text" for the kind of lessons we are working right now.  

Wondering whether we should include course name, title and author details in the course.json or metadata.json. Let's keep it in both places for now and go ahead.

**Comment by nikochiko** [comment]
I think the format mentioned above is too flexible and makes it harder to manage relative links.
I haven't come to a good solution for handling relative links or links from one lesson file to another.
IMO, we should keep links between lessons and non-HTML lessons out of scope.

For handling static assets, I'm proposing that we have a `contents/static` directory and anything inside it will be served as it is under some URL prefix. Any lesson can reach the static directory with `../../../static` as the URL prefix. We can use this in the compilation step.

The new directory format would look like this:

```
metadata.json
contents/
|-- course.json
|-- modules/
|   |-- module_1
|   |   |-- lesson_1.html
|   |   |-- lesson_2.html
|-- static/
|   |-- img.jpg
```

**Comment by anandology** [comment]
> IMO, we should keep links between lessons and non-HTML lessons out of scope.

Yes, that is out of scope for now.

> For handling static assets, I'm proposing that we have a `contents/static` directory and anything inside it will be served as it is under some URL prefix. Any lesson can reach the static directory with `../../static` as the URL prefix. We can use this in the compilation step.

Call it `media` instead of  `static`.

> i.e., route for a lesson: `/courses/<course-name>/lessons/<module-name>/<lesson-name>` (should /lessons/ be something else or nothing) ? 

` /courses/<course-name>/<module-name>/<lesson-name>`  for now.

> route for static files: `/courses/<course-name>/static/a.jpg`

`/courses/<course-name>/media/a.jpg`

**Comment by nikochiko** [comment]
The two routes would conflict with each other.

`/courses/<course-name>/<module-name>/<lesson-name>`
and
`/courses/<course-name>/media/a.jpg`

I think we should have some prefix for the lesson route.

**Comment by anandology** [comment]
> I think we should have some prefix for the lesson route.

Then relative links will not work for media.  You can keep the route for media first and then add the other one.

**Comment by nikochiko** [comment]
Handlers for this have been added to the repository.

Courses in this format can be loaded, along with their assets, to the capstone app.

**Comment by nikochiko** [comment]
This is done. Next versions of it should be formed by iterating with separate issues
