### ISSUE TITLE
Start Project without login should not leave the page

### ISSUE THREAD

**Issue by anandology** [pipalacademy/capstone#70]
## The issue

If you click on "Start Project" button on a project page without logging in, it redirects to google oauth login and redirects to dashboard after login. 

## Expected behavior

It should redirect back to the project page.

## How to Reproduce

* Visit https://capstone-staging.pipal.in/ 
* Log out if you are logged in
* Go to project "Fortune"
* Click on "Start Project"
* Login using Google Oauth
* You are redirected to /dashboard

## Comments

The Logout also has the same issue. After logout, you should come back to the same page.

**Comment by nikochiko** [comment]
fixed in https://github.com/pipalacademy/capstone/commit/0befa3f5ddd2d5c2001c3e98a51b642a7ad1d10f
